name: Generate GitHub Stats Image

on:
  schedule:
    - cron: '0 0 * * *'  # Every Day 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch GitHub Stats SVG
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               "https://github-readme-stats.vercel.app/api?username=leegisang&count_private=true&show_icons=true&hide_border=true" \
               --output stats.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats" || echo "No changes"
          git push
